### DISCUSSION TITLE
How to make nodes in Ready status?

### DISCUSSION THREAD

**Discussion by kenorb** [PyratLabs/ansible-role-k3s#160] [Q&A] [answered]
After applying role, my node has NotReady status and it shows 0 limits for CPU and 170MB for memory.
How I can make my node in Ready state? Maybe it's due to the CPU or memory limits?

```
$ kubectl describe node mynode | tail -n10
...
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----                 ------    -----------------                 ------------------                ------              -------
  NetworkUnavailable   False     Sun, 03 Oct 2021 23:12:38 +0200   Sun, 03 Oct 2021 23:12:38 +0200   FlannelIsUp         Flannel is running on this node
  MemoryPressure       Unknown   Sun, 03 Oct 2021 23:12:13 +0200   Sun, 03 Oct 2021 23:17:49 +0200   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure         Unknown   Sun, 03 Oct 2021 23:12:13 +0200   Sun, 03 Oct 2021 23:17:49 +0200   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure          Unknown   Sun, 03 Oct 2021 23:12:13 +0200   Sun, 03 Oct 2021 23:17:49 +0200   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready                Unknown   Sun, 03 Oct 2021 23:12:13 +0200   Sun, 03 Oct 2021 23:17:49 +0200   NodeStatusUnknown   Kubelet stopped posting node status.
Capacity:
  cpu:                6
  ephemeral-storage:  2062223816Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             30823708Ki
  pods:               110
Allocatable:
  cpu:                6
  ephemeral-storage:  2006131326632
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             30823708Ki
  pods:               110
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                100m (1%)  0 (0%)
  memory             70Mi (0%)  170Mi (0%)
  ephemeral-storage  0 (0%)     0 (0%)
  hugepages-1Gi      0 (0%)     0 (0%)
  hugepages-2Mi      0 (0%)     0 (0%)
```

Config:

```
---
- hosts: vm01
  roles:
    - role: xanmanning.k3s
      vars:
        k3s_become_for_all: true
        k3s_etcd_datastore: yes
        k3s_server:
          disable:
            - coredns
            - local-storage
            - metrics-server
            - servicelb
            - traefik
          flannel-backend: 'none'
          write-kubeconfig-mode: 640
        k3s_state: installed
```

Other info:

```
local$ ansible-galaxy list xanmanning.k3s
- xanmanning.k3s, v2.11.0
vm01$ grep -E ^cpuset\\s+.*\\s+1$ /proc/cgroups
cpuset	9	4	1
vm01$ grep -E ^memory\\s+.*\\s+1$ /proc/cgroups
memory	12	97	1
```

In general I think that's the reason why my node is in `NotReady` state.

**Comment by xanmanning** [comment, marked as answer]
First thing, have you applied a CNI? Nodes will not be ready until you have a CNI.

**Reply by kenorb** [reply]
Thanks, it worked after adding:

```
        k3s_server_manifests_urls:
          - filename: tigera-operator.yaml
            url: https://docs.projectcalico.org/manifests/tigera-operator.yaml
          - filename: calico.yaml
            url: https://docs.projectcalico.org/manifests/calico.yaml
        k3s_server_pod_manifests_urls:
          - filename: kube-vip.yaml
            url: https://github.com/kube-vip/kube-vip/blob/main/example/deploy/0.3.5.yaml
```
