### DISCUSSION TITLE
How can i set --node-ip and --node-external-ip to each node on install

### DISCUSSION THREAD

**Discussion by KorzunKarl** [PyratLabs/ansible-role-k3s#215] [Q&A] [answered]
When i install new cluster - with two interfases on hosts, how can i set internal ip and external ip adersses on cluster install whith this role, please help ).

**Comment by KorzunKarl** [comment, marked as answer]
Since I myself asked a very stupid question, I will answer it myself.  )))


```
k3s_control_plane:
  vars:
    k3s_become: true
    k3s_release_version: v1.28.2+k3s1
    k3s_etcd_datastore: true
    k3s_controller_list: ['node-01', 'node-02']
    k3s_server:
      bind-address: 0.0.0.0
      write-kubeconfig-mode: '0644'
      node-ip: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
      node-external-ip: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}"
      node-label:
        - "NodeTier=node"
        - "NodeLocation=debug"
        - "NodeCustomRole=master"
      disable:
        - traefik
  hosts:
    node-01:
      ansible_user: awx
      ansible_host: 10.11.0.10
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    node-02:
      ansible_user: awx
      ansible_host: 10.11.0.11
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true

```

This is example of config --node-ip and --node-external-ip
