### ISSUE TITLE
Command tasks fail for ansible == 2.9.16

### ISSUE THREAD

**Issue by py-t** [PyratLabs/ansible-role-k3s#105]
### Summary
In the newest Release (k3s
Ansible does not seem to handle `ansible.builtin.command` blocks in the role right

### Issue Type

- Bug Report

### Controller Environment and Configuration

- `ansible==2.9.16`, no extra config
- role: `2.8.1`

### Steps to Reproduce

```yaml

- hosts: all
  roles:
    - xanmanning.k3s

```

The following task fails: `validate/configuration/unsupported-rootless.yml` -> `Check if newuidmap is available`:
```
{"reason": "this task 'ansible.builtin.command' has extra params, which is only allowed in the following modules: ansible.legacy.add_host, ansible.legacy.import_tasks, ansible.legacy.include_tasks, set_fact, ansible.builtin.include_vars, include_tasks, ansible.legacy.set_fact, ansible.builtin.include, meta, ansible.legacy.include_vars, ansible.builtin.include_tasks, import_tasks, command, add_host, ansible.legacy.import_role, ansible.builtin.add_host, group_by, ansible.builtin.meta, win_shell, include, ansible.builtin.set_fact, import_role, shell, include_role, ansible.legacy.group_by, ansible.legacy.include_role, ansible.legacy.meta, include_vars, ansible.builtin.group_by, raw, ansible.builtin.import_tasks, ansible.builtin.import_role, win_command, script, ansible.builtin.include_role, ansible.legacy.include\n\nThe error appears to be in '/home/ilya/ng/deployment/k3s-cluster/ansible_roles/xanmanning.k3s/tasks/validate/environment/local/issue-data.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Ansible version is captured\n  ^ here\n"}
```

### How to fix

The error is fixed by changing the task into (putting the command into `cmd` key):

```
- name: Check if newuidmap is available
  ansible.builtin.command:
    cmd: "which newuidmap"
  failed_when: false
  changed_when: false
  register: k3s_check_newuidmap_installed
```

Same is valid for other command tasks

**Comment by samcat116** [comment]
Also happens to me on Ansible 2.10

**Comment by xanmanning** [comment]
2.9.16 relates to this bug: https://github.com/ansible/ansible/pull/72958
<=2.10.3 relates to this bug: https://github.com/ansible/ansible/pull/71824

This...

```yaml
- name: Check if newuidmap is available
  ansible.builtin.command:
    cmd: "which newuidmap"
  failed_when: false
  changed_when: false
  register: k3s_check_newuidmap_installed
```

Was spotty in terms of whether it worked or not in 2.9 and 2.10 releases until both those bugs were closed, hence why I set this:

https://github.com/PyratLabs/ansible-role-k3s#requirements

and builds pass: https://github.com/PyratLabs/ansible-role-k3s/actions/runs/715024863

I will look into seeing how far back I can implement using "cmd" - however I am tied up in other engagements at the moment...
