### ISSUE TITLE
secondary controllers registration errors

### ISSUE THREAD

**Issue by senorsmile** [PyratLabs/ansible-role-k3s#106]
### Summary

I am testing with a 6 node cluster in Vagrant. 
3 controller nodes. 
3 agents. 

The first controller comes up okay, but the other 2 time out. 

I went into controller 2, copied the line from /etc/systemd/systemd/k3s.service and ran it and got: 
```#
# /usr/local/bin/k3s server --server https://192.168.85.101:6443 --token-file /etc/rancher/k3s/cluster-token --config /etc/rancher/k3s/config.yaml

INFO[2021-04-08T14:13:15.236433093Z] Starting k3s v1.20.5+k3s1 (355fff30)         
INFO[2021-04-08T14:13:15.277972316Z] Managed etcd cluster not yet initialized     
FATA[2021-04-08T14:13:15.288235958Z] starting kubernetes: preparing server: start managed database: joining etcd cluster: etcdclient: no available endpoints
```

on controller1, I see etcd is up and advertising: 
```#
# ss -lnp | grep 2379

tcp                LISTEN              0                    4096                                                                                      127.0.0.1:2379                                              0.0.0.0:*                      users:(("k3s-server",pid=8614,fd=10))                                          
tcp                LISTEN              0                    4096                                                                                      10.0.2.15:2379                                              0.0.0.0:*                      users:(("k3s-server",pid=8614,fd=9))                                           
```

### Issue Type

- Bug Report

### Controller Environment and Configuration

```#yml
# Begin ANSIBLE VERSION
ansible 2.9.19
  config file = None
  configured module search path = ['/home/senorsmile/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/senorsmile/.local/share/virtualenvs/k3s-pyratlabs-it8gg1QU/lib/python3.6/site-packages/ansible
  executable location = /home/senorsmile/.local/share/virtualenvs/k3s-pyratlabs-it8gg1QU/bin/ansible
  python version = 3.6.12 (default, Feb 14 2021, 11:31:45) [GCC 10.2.0]
# End ANSIBLE VERSION

# Begin ANSIBLE CONFIG
DEFAULT_CALLBACK_WHITELIST(env: ANSIBLE_CALLBACK_WHITELIST) = ['timer', 'profile_tasks']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
# End ANSIBLE CONFIG

# Begin ANSIBLE ROLES
usage: ansible-galaxy [-h] [--version] [-v] TYPE ...

Perform various Role and Collection related operations.

positional arguments:
  TYPE
    collection   Manage an Ansible Galaxy collection.
    role         Manage an Ansible Galaxy role.

optional arguments:
  --version      show program's version number, config file location,
                 configured module search path, module location, executable
                 location and exit
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
# End ANSIBLE ROLES

# Begin PLAY HOSTS
["vagrant_k3s_master01", "vagrant_k3s_master02", "vagrant_k3s_master03", "vagrant_k3s_node01", "vagrant_k3s_node02"]
# End PLAY HOSTS

# Begin K3S ROLE CONFIG
## vagrant_k3s_master01
k3s_become_for_all: true
k3s_install_hard_links: true
k3s_release_version: "v1.20.5+k3s1"
k3s_state: "installed"
k3s_advertise_address: "192.168.85.101"
k3s_node_external_address: "192.168.85.101"
k3s_node_ip_address: "192.168.85.101"
k3s_registration_address: "192.168.85.101"
k3s_control_node: true
k3s_etcd_datastore: true

## vagrant_k3s_master02
k3s_become_for_all: true
k3s_install_hard_links: true
k3s_release_version: "v1.20.5+k3s1"
k3s_state: "installed"
k3s_advertise_address: "192.168.85.102"
k3s_node_external_address: "192.168.85.102"
k3s_node_ip_address: "192.168.85.102"
k3s_registration_address: "192.168.85.101"
k3s_control_node: true
k3s_etcd_datastore: true

## vagrant_k3s_master03
k3s_become_for_all: true
k3s_install_hard_links: true
k3s_release_version: "v1.20.5+k3s1"
k3s_state: "installed"
k3s_advertise_address: "192.168.85.103"
k3s_node_external_address: "192.168.85.103"
k3s_node_ip_address: "192.168.85.103"
k3s_registration_address: "192.168.85.101"
k3s_control_node: true
k3s_etcd_datastore: true

## vagrant_k3s_node01
k3s_become_for_all: true
k3s_install_hard_links: true
k3s_release_version: "v1.20.5+k3s1"
k3s_state: "installed"
k3s_advertise_address: "192.168.85.111"
k3s_node_external_address: "192.168.85.111"
k3s_node_ip_address: "192.168.85.111"
k3s_registration_address: "192.168.85.101"
k3s_control_node: false

## vagrant_k3s_node02
k3s_become_for_all: true
k3s_install_hard_links: true
k3s_release_version: "v1.20.5+k3s1"
k3s_state: "installed"
k3s_advertise_address: "192.168.85.112"
k3s_node_external_address: "192.168.85.112"
k3s_node_ip_address: "192.168.85.112"
k3s_registration_address: "192.168.85.101"
k3s_control_node: false

# End K3S ROLE CONFIG

# Begin K3S RUNTIME CONFIG
## vagrant_k3s_master01
## vagrant_k3s_master02
## vagrant_k3s_master03
## vagrant_k3s_node01
## vagrant_k3s_node02
# End K3S RUNTIME CONFIG
```

```text
* a3c4d9c - (HEAD -> main, tag: v2.8.1, origin/main, origin/HEAD) Updated CHANGELOG (2 weeks ago) <Xan Manning>
```

### Steps to Reproduce

Here's my inventory
```yaml
---
k3s:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
    ansible_become_pass: vagrant
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
   
    k3s_become_for_all: True
    k3s_install_hard_links: True
    k3s_release_version: "v1.20.5+k3s1"
    k3s_state: installed
    k3s_advertise_address: "{{ ansible_host }}"
    k3s_node_external_address: "{{ ansible_host }}"
    k3s_node_ip_address: "{{ ansible_host }}"

    k3s_registration_address: 192.168.85.101


  children:
    k3s_masters:
      vars:
        k3s_control_node: True
        k3s_etcd_datastore: True # embedded replicated etcd
      hosts:
        vagrant_k3s_master01:
          ansible_host: 192.168.85.101
        vagrant_k3s_master02:
          ansible_host: 192.168.85.102
        vagrant_k3s_master03:
          ansible_host: 192.168.85.103

    k3s_nodes:
      vars:
        k3s_control_node: False
      hosts:
        vagrant_k3s_node01:
          ansible_host: 192.168.85.111
        vagrant_k3s_node02:
          ansible_host: 192.168.85.112
        vagrant_k3s_node02:
          ansible_host: 192.168.85.112
```

### Expected Result

all checks should pass because service came up properly.  

### Actual Result

```text
TASK [Pyratlabs.k3s : Check that the control plane is available to accept connections] **********************************************************************
Thursday 08 April 2021  06:48:39 -0700 (0:00:08.346)       0:01:04.897 ******** 
skipping: [vagrant_k3s_node01]
skipping: [vagrant_k3s_node02]
ok: [vagrant_k3s_master01]
fatal: [vagrant_k3s_master02]: FAILED! => changed=false 
  elapsed: 300
  msg: Timeout when waiting for 127.0.0.1:6443
fatal: [vagrant_k3s_master03]: FAILED! => changed=false 
  elapsed: 300
  msg: Timeout when waiting for 127.0.0.1:6443
[WARNING]: flush_handlers task does not support when conditional
```

**Comment by xanmanning** [comment]
Invalid configuration variables...

```yaml
    k3s_advertise_address: "{{ ansible_host }}"
    k3s_node_external_address: "{{ ansible_host }}"
    k3s_node_ip_address: "{{ ansible_host }}"
```

These should be set under `k3s_server` and `k3s_agent` dictionary

Here's an example, sorry tt's a bit scrappy, this is a personal project I have been mucking about with: https://github.com/xanmanning/vagrant-kubernetes-cluster/blob/master/playbooks/kube-bootstrap.yml#L20-L43
