### ISSUE TITLE
Problems when using docker as the container runtime

### ISSUE THREAD

**Issue by whillas** [PyratLabs/ansible-role-k3s#108]
### Summary

i'm getting this:
```
 __________________________________________________________
< TASK [xanmanning.k3s : Ensure Docker APT key is present] >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [192.168.178.75]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key add -", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\nE: This command can only be used by root.", "rc": 1, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\nE: This command can only be used by root.\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "E: This command can only be used by root."], "stdout": "", "stdout_lines": []}
```
I need docker as a runtime container. Is there a way to turn off the docker checks as i have my own docker setup?

### Issue Type

- Bug Report

### Controller Environment and Configuration

```text
# Begin ANSIBLE VERSION
ansible 2.10.7
  config file = /home/alex/dev/imagr/ml-edge/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alex/.local/lib/python3.8/site-packages/ansible
  executable location = /home/alex/.local/bin/ansible
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]
# End ANSIBLE VERSION

# Begin ANSIBLE CONFIG

# End ANSIBLE CONFIG

# Begin ANSIBLE ROLES
# /home/alex/.ansible/roles
- ahuffman.resolv, 1.3.2
- xanmanning.k3s, v2.8.2
- ebesson.k3s, master
# End ANSIBLE ROLES

# Begin PLAY HOSTS
["192.168.178.75"]
# End PLAY HOSTS

# Begin K3S ROLE CONFIG
## 192.168.178.75
k3s_check_cgroup_option: {"cmd": ["grep", "-E", "^cpuset\\s+.*\\s+1$", "/proc/cgroups"], "stdout": "cpuset\t8\t2\t1", "stderr": "", "rc": 0, "start": "2021-04-12 07:20:22.138754", "end": "2021-04-12 07:20:22.143011", "delta": "0:00:00.004257", "changed": false, "stdout_lines": ["cpuset\t8\t2\t1"], "stderr_lines": [], "failed": false, "failed_when_result": false}

# End K3S ROLE CONFIG

# Begin K3S RUNTIME CONFIG
## 192.168.178.75
# End K3S RUNTIME CONFIG
```

### Steps to Reproduce

 the playbook is
```yaml
- name: K3S
  hosts: all
  become: true
  vars:
    k3s_release_version: v1.19.9+k3s1
    # standalone system, and not a cluster
    k3s_build_cluster: false
    k3s_server:
      docker: true
      kube-apiserver-arg: service-node-port-range=1-65000
      write-kubeconfig: ~/.kube/config
      write-kubeconfig-mode: 666
  roles:
     - xanmanning.k3s
   ```
I also had to include this in my playbooks else i couldn't get passed the persmision denied messages
```yaml
- name: K3S docker deps
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Ensure Docker APT key is present
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Ensure Docker repository is installed and configured
  ansible.builtin.apt_repository:
    filename: docker-ce
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: true
```
I manage the install of docker myself as i need to get the NVIDIA runtime container as the node(s) have GPUs i need access to.
