### ISSUE TITLE
Docs: Deploy kube-vip as the Control-plane HA load balancer

### ISSUE THREAD

**Issue by onedr0p** [PyratLabs/ansible-role-k3s#117]
### Summary

It would be cool if this role could have an option to install [kube-vip](https://github.com/kube-vip/kube-vip)

### Issue Type

- Feature Request

### User Story

The install process would be something like:

1) Install first master
2) install kube-vip as static pod
3) join other masters and workers to the VIP

See here for a more detailed explanation:
https://cncn.io/2021/03/ha-k3s-with-kube-vip-and-metallb/

**Comment by bjw-s** [comment]
I'm not sure if the static pod would work for k3s. The official kube-vip install guide makes use of a DaemonSet approach:
https://kube-vip.io/control-plane/#k3s

**Comment by onedr0p** [comment]
@xanmanning @bjw-s Technically this can already be done with the `k3s_server_manifests_templates` configuration option:

```yaml
k3s_server_manifests_templates:
- kube-vip-rbac.yaml.j2
- kube-vip-daemonset.yaml.j2
```

However I believe that we should set `run_once: true` on the following block of code because only the first control plane nodes should have these manifests. Or is there a better way to force only the first control plane node to accept manifests via this option?

```yaml
# https://rancher.com/docs/k3s/latest/en/advanced/#auto-deploying-manifests
- name: Ensure auto-deploying manifests are copied to controllers
  run_once: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  loop: "{{ k3s_server_manifests_templates }}"
  become: "{{ k3s_become_for_directory_creation | ternary(true, false, k3s_become_for_all) }}"
```

After we discuss that, I think it's just a matter of documention in the README showing people _how_ they can use kube-vip.
