### ISSUE TITLE
3 node HA Cluster node 2 and  node3 don't start

### ISSUE THREAD

**Issue by babvin** [PyratLabs/ansible-role-k3s#127]
TASK [xanmanning.k3s : Check that the control plane is available to accept connections] ***********************************************************************************************
ok: [kube-0]
fatal: [kube-2]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1:6443"}
fatal: [kube-1]: FAILED! => {"changed": false, "elapsed": 302, "msg": "Timeout when waiting for 127.0.0.1:6443"}
[WARNING]: flush_handlers task does not support when conditional

TASK [xanmanning.k3s : Check that all nodes to be ready] ******************************************************************************************************************************
ok: [kube-0]

PLAY RECAP ****************************************************************************************************************************************************************************
kube-0                     : ok=69   changed=0    unreachable=0    failed=0    skipped=41   rescued=0    ignored=0   
kube-1                     : ok=56   changed=0    unreachable=0    failed=1    skipped=41   rescued=0    ignored=0   
kube-2                     : ok=56   changed=0    unreachable=0    failed=1    skipped=41   rescued=0    ignored=0   

Jun  4 10:01:52 ubuntu-hirsute systemd[1]: Stopped Lightweight Kubernetes.
Jun  4 10:01:52 ubuntu-hirsute systemd[1]: Starting Lightweight Kubernetes...
Jun  4 10:01:52 ubuntu-hirsute k3s[14113]: time="2021-06-04T10:01:52.882339901Z" level=info msg="Starting k3s v1.21.1+k3s1 (75dba57f)"
Jun  4 10:01:52 ubuntu-hirsute k3s[14113]: time="2021-06-04T10:01:52.922017458Z" level=info msg="Managed etcd cluster not yet initialized"
Jun  4 10:01:52 ubuntu-hirsute k3s[14113]: time="2021-06-04T10:01:52.934499947Z" level=fatal msg="starting kubernetes: preparing server: start managed database: joining etcd cluster: etcdclient: no available endpoints"
Jun  4 10:01:52 ubuntu-hirsute systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jun  4 10:01:52 ubuntu-hirsute systemd[1]: k3s.service: Failed with result 'exit-code'.
Jun  4 10:01:52 ubuntu-hirsute systemd[1]: Failed to start Lightweight Kubernetes.
Jun  4 10:01:54 ubuntu-hirsute multipathd[481]: sdb: add missing path
Jun  4 10:01:54 ubuntu-hirsute multipathd[481]: sdb: failed to get sysfs uid: No data available
Jun  4 10:01:54 ubuntu-hirsute multipathd[481]: sdb: failed to get sgio uid: No data available

k3s_cluster:
  hosts:
    kube-0:
      ansible_user: vagrant
      ansible_host: 192.168.10.11
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    kube-1:
      ansible_user: vagrant
      ansible_host: 192.168.10.12
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    kube-2:
      ansible_user: vagrant
      ansible_host: 192.168.10.13
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true

---

- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true  # Note this is required for k3s < v1.19.5+k3s1
  roles:
    - role: xanmanning.k3s

**Comment by xmanningcentiq** [comment]
What is your network topology for Vagrant? Presumably you have a host only adaptor for the `192.168.10.0/24` range? I believe K3S by default will bind to the first network interface which is not an issue in the role but default behaviour for K3S.

Try the following configuration globally - this has fixed it for me when running in Vagrant:

```yaml
---

k3s_server:
  advertise-address: "{{ ansible_host }}"
  bind-address: 0.0.0.0

k3s_agent:
  node-ip: "{{ ansible_host }}"
  node-external-ip: "{{ ansible_host }}"
```

**Comment by babvin** [comment]
Thanks for the quick reply can you please suggest where to add this global
entry to which file?

**Comment by xmanningcentiq** [comment]
Perhaps try in your playbook?

```yaml
---

- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true # Note this is required for k3s < v1.19.5+k3s1
    k3s_server:
      advertise-address: "{{ ansible_host }}"
      bind-address: 0.0.0.0

    k3s_agent:
      node-ip: "{{ ansible_host }}"
      node-external-ip: "{{ ansible_host }}"
  roles:
    role: xanmanning.k3s
```
