### ISSUE TITLE
"msg": "file not found: /var/lib/rancher/k3s/server/token"

### ISSUE THREAD

**Issue by houshym** [PyratLabs/ansible-role-k3s#144]
### Summary

I try to setup a 2 node cluster, one master and one worrker

### Issue Type

- Bug Report

I can see 2 errors
```
1-
TASK [xanmanning.k3s : Check the conditions when a single controller is defined] ************************************************************************************************
task path: /Users/msarvestani/.ansible/roles/xanmanning.k3s/tasks/validate/configuration/control-node-count.yml:3
Read vars_file '../vars/main.yml'
fatal: [kube-0]: FAILED! => {
    "assertion": "(k3s_etcd_datastore is not defined or not k3s_etcd_datastore)",
    "changed": false,
    "evaluated_to": false,
    "msg": "Control plane configuration is invalid. Please see notes about k3s_control_node and HA in README.md."
}
```

```
2-  TASK [xanmanning.k3s : Ensure cluster token is captured from kube-0]
```
The full traceback is:
  File "/tmp/ansible_ansible.builtin.slurp_payload_chs17y9c/ansible_ansible.builtin.slurp_payload.zip/ansible/modules/slurp.py", line 97, in main
fatal: [kube-1 -> kube-0]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "path": "/var/lib/rancher/k3s/server/token",
            "src": "/var/lib/rancher/k3s/server/token"
        }
    },
    "msg": "file not found: /var/lib/rancher/k3s/server/token"
}
```

### Controller Environment and Configuration

# Begin ANSIBLE VERSION
ansible [core 2.11.2]
  config file = None
  configured module search path = ['/Users//.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.2.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/i/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
# End ANSIBLE VERSION

# Begin ANSIBLE CONFIG

# End ANSIBLE CONFIG

# Begin ANSIBLE ROLES
# 
- xanmanning.k3s, v2.10.2
# End ANSIBLE ROLES

# Begin PLAY HOSTS
["kube-0", "kube-1"]
# End PLAY HOSTS

# Begin K3S ROLE CONFIG
## kube-0
k3s_control_node: true
k3s_check_cgroup_option: {"cmd": ["grep", "-E", "^cpuset\\s+.*\\s+1$", "/proc/cgroups"], "stdout": "cpuset\t7\t139\t1", "stderr": "", "rc": 0, "start": "2021-08-20 23:50:12.375160", "end": "2021-08-20 23:50:12.378838", "delta": "0:00:00.003678", "changed": false, "stdout_lines": ["cpuset\t7\t139\t1"], "stderr_lines": [], "failed": false, "failed_when_result": false}

## kube-1
k3s_control_node: false
k3s_check_cgroup_option: {"cmd": ["grep", "-E", "^cpuset\\s+.*\\s+1$", "/proc/cgroups"], "stdout": "cpuset\t6\t138\t1", "stderr": "", "rc": 0, "start": "2021-08-20 23:50:12.191833", "end": "2021-08-20 23:50:12.195929", "delta": "0:00:00.004096", "changed": false, "stdout_lines": ["cpuset\t6\t138\t1"], "stderr_lines": [], "failed": false, "failed_when_result": false}

# End K3S ROLE CONFIG

# Begin K3S RUNTIME CONFIG
## kube-0
## kube-1
# End K3S RUNTIME CONFIG



```text

```

### Steps to Reproduce

inventory
```
k3s_cluster:
  hosts:
    kube-0:
      ansible_user: skyline
      ansible_host: 172.28.12.134
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    kube-1:
      ansible_user: skyline
      ansible_host: 172.28.12.135
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false

```

platbook
```
- name: Build a single node k3s cluster
  hosts: k3s_cluster
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ../vars/main.yml
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_install_hard_links: true
    k3s_build_cluster: true
    k3s_server:
      write-kubeconfig-mode: 664
      service-node-port-range: 0-40000
      cluster-cidr: 172.24.0.0/16
#      flannel-backend: 'wireguard'  # This needs to be in quotes for some reason
    # k3s_state: installed
    # k3s_advertise_address: "{{ ansible_host }}"
    # k3s_node_external_address: "{{ ansible_host }}"
    # k3s_node_ip_address: "{{ ansible_host }}"
    # k3s_registration_address: 192.168.85.101   

    ansible_python_interpreter: /usr/bin/python3
   
  roles:
    - role: xanmanning.k3s
      k3s_release_version: "{{ k3s_version }}"
      k3s_install_dir: /usr/local/bin
      k3s_use_experimental: true
#      using k3s_server.yaml as a config file  https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
#      k3s_server: "{{ lookup('file', 'path/to/k3s_server.yml') | from_yaml }}"
      k3s_server:
        disable:
          - traefik
          - servicelb
        kubelet-arg: feature-gates=EphemeralContainers=true
        kube-apiserver-arg: feature-gates=EphemeralContainers=true
        kube-controller-manager-arg: feature-gates=EphemeralContainers=true
        kube-scheduler-arg: feature-gates=EphemeralContainers=true
```
### Expected Result

to set up a 2 node cluster. one node as a controller and 1 node as an agent.
I tried both versions.  v1.21.4+k3s1 and v1.21.2+k3s1

```

```

### Actual Result

```

```
