### ISSUE TITLE
Enchancement: Document IPv6 options with the playbook

### ISSUE THREAD

**Issue by samip5** [PyratLabs/ansible-role-k3s#147]
### Summary

I would like there be documented options for specifying dual-stack install, with IPv4 and IPv6. The feature is heading stable in Kubernetes v1.23 (https://github.com/kubernetes/kubernetes/pull/104691).

### Issue Type

- Feature Request

### User Story

_As a_ sysadmin \
_I want to_ be able to configure dual-stack properly using the Ansible playbook \
_So that_ IPv6 is the primary IP family

**Comment by xanmanning** [comment]
Dual-stack support isn't available in K3S yet?

https://github.com/k3s-io/k3s/pull/3906

**Comment by samip5** [comment]
> Dual-stack support isn't available in K3S yet?
> 
> [k3s-io/k3s#3906](https://github.com/k3s-io/k3s/pull/3906)

I'm running services with dual-stack on k3s, it's not perfect but there is some support already thanks to the upstream kubernetes changes.

**Comment by samip5** [comment]
Related: https://github.com/k3s-io/k3s/issues/1405#issuecomment-900534320

**Comment by xanmanning** [comment]
So presumably, you're running k3s with options such as (pardon the poor IPv6 address example):

```yaml
k3s_server:
  flannel-backend: 'none'
  cluster-cidr: 10.42.0.0/16,fc00:a0::/64
  service-cidr: 10.43.0.0/16,fc00:a1::/64
```
