### ISSUE TITLE
Support for the special config.yaml.d directory

### ISSUE THREAD

**Issue by onedr0p** [PyratLabs/ansible-role-k3s#148]
### Summary

k3s supports a `config.yaml.d` under the `/etc/rancher/k3s` directory which allow to split up the configuration a bit. It would be cool if this was supported here.

### Issue Type

- Feature Request

### User Story

As a user I would like to deploy additional k3s configuration to the `config.yaml.d`. My major use case for this is that I can have a file that is encrypted with ansible vault or mozilla sops.

Consider the following file gets copied into the `/etc/rancher/k3s/config.yaml.d` directory. The Ansible variables I have here are decrypted on the fly from SOPS.

```yaml
# 10-etcd-snapshots.yml.j2
etcd-snapshot-schedule-cron: "{{ etcd_snapshot_schedule_cron }}"
etcd-snapshot-retention: "{{ etcd_snapshot_retention }}"
etcd-s3: "{{ etcd_s3 }}"
etcd-s3-endpoint: "{{ etcd_s3_endpoint }}"
etcd-s3-bucket: "{{ etcd_s3_bucket }}"
etcd-s3-access-key: "{{ etcd_s3_access_key }}"
etcd-s3-secret-key: "{{ etcd_s3_secret_key }}"
```

### Additional Information

https://github.com/k3s-io/k3s/issues/3205
