### ISSUE TITLE
Allow passing a specific host to be configured via role variables

### ISSUE THREAD

**Issue by frgomes** [PyratLabs/ansible-role-k3s#155]
### Summary

Ability to provision k3s to a dynamically created virtual machine, in cases where IP addresses are allocated dynamically and obviously no known beforehand. The idea would be passing all parameters via role vars, including IP addresses of virtual machines where k3s should be installed.

### Issue Type

- Feature Request / Question

### User Story

An automated system provisions virtual machines dynamically in such a way that IP addresses are dynamic and discovered along the way. The playbook then obtains the IP address and performs tasks by passing the IP address explicitly to tasks and roles via role variables.

```yaml
    # This is an example. It will not work.
    # Do not blindly copy/paste this code into your playbook!
    - include_role:
        name: xanmanning.k3s
      vars:
        hosts:
          vm:
            ansible_host: "{{dynamically_allocated_ip_address}}"
            ansible_user: "some_username"
        k3s_build_cluster: false
```

**Comment by xanmanning** [comment]
Aren't `ansible_host` and `ansible_user` just core variables to Ansible? Ansible needs to know these in order to connect to a system, be it defined in a static inventory or in a dynamic inventory?

This sounds out of scope of the role and more to do with how you set up your Ansible project.

**Comment by frgomes** [comment]
@xanmanning :: As far as I know  [ansible_host cannot be overriden](https://github.com/ansible/ansible/issues/18359).

This is a minimalist test case:

```yaml
---
- name: ansible_host cannot be redefined
  hosts: localhost

  tasks:

    - name: set facts -- admin_hostname
      set_fact:
        admin_hostname: "{{lookup('pipe','hostname')}}"
     
    - name: debug
      debug:
        msg: "admin_hostname is {{admin_hostname}}"

    # - name: Provisioning using Terraform and obtain target IP address
    #   blah:
    #  
    # - name: wait for provisioned host to become available
    #   blah:
    #   
    # - name: obtain host key and insert in our ~/.ssh/known_hosts
    #   blah:
      
    - name: set facts -- ansible_host
      set_fact:
        ansible_host: "192.168.3.152" # supposedly the target IP address
        
    - name: set facts -- ansible_user
      set_fact:
        ansible_user: "autorun" # a valid user on the target IP address
      
    - name: set facts -- target_hostname
      set_fact:
        target_hostname: "{{lookup('pipe','hostname')}}"

    - name: debug
      debug:
        msg: "target_hostname is {{target_hostname}}"
```

**Comment by xanmanning** [comment]
That's my point, `ansible_host` is a core Ansible variable which comes from inventory (static or dynamic). I don't understand why you're trying to pass it to the role, the role can already see it because Ansible creates these variables during setup phase.

What are you wanting the role to do?

**Comment by frgomes** [comment]
@xanmanning :: I don't know any IP address in advance. I don't have any inventory to populate or any variable to initialize simply because I don't know any IP address in advance. IP addresses are discovered along the way as shown in the use case above.

Would it make sense to change ``ansible-role-k3s`` so that a host and a user are enforced, pretty much all over the place, something like this below?

```yaml

 - name: something
   whatever:
      it_is: blah
   delegate_to: "{{target_ip | default(ansible_host)}}"
   remote_user: "{{target_user | default(ansible_user)}}"
 ```
 
 I offer to do the change, if you think makes sense and you provide me some guidance.
 
 Thanks

**Comment by xanmanning** [comment]
I think I need to understand more about what you're doing, how do you use other roles? Eg. How would you implement the use of `geerlingguy.docker` for example? It doesn't use `delegate_to:` everywhere (because that is just a bit bananas).

How does Ansible know what to connect to? At some point be it statically or [dynamically](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html), you need to tell Ansible which system to connect to and how. What in your workflow does this? Can it assign hosts to a group? [Example of AWS dynamic inventory](https://devopscube.com/setup-ansible-aws-dynamic-inventory/) where you might not know the IP/Hostname but you you can assign hosts to groups, in the context of this role you can assign some control plane nodes to one group and workers to another.

The reason why I'm asking is that you can define the `k3s_` variables in [host vars, or group vars](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#splitting-out-vars) to apply to the target system.

**Comment by frgomes** [comment]
The use case is the following:

* My playbook does not need any inventory. The only host I'm interested is ``localhost`` running on the current user, which is the default.

* There is another host which is of interest: let's call it: **kvm-host**. This host runs ``KVM/libvirt`` and it is responsible for provisioning and running virtual machines in my home lab. I connect to this host via ``KVM/libvirt`` protocol. Ansible is absolutely oblivious about **kvm-host**, since Ansible does not fire a single command against this host.

* I'm provisioning virtual machines on KVM/libvirt via ``ansible.plugins.terraform``, which speaks ``KVM/libvirt`` protocol, not SSH/Ansible protocol, being absolutely oblivious of any business which could possibly resemble the concept of "inventory". Once again: I do not have any inventory, not even a vars file which Ansible could retrieve IP addresses or hostnames in order to connect to. I do have a file which describes the virtual machine to be provisioned, but I do not have its IP address, since the IP address is allocated dynamicaly. I do have its hostname... but Ansible cannot connect to it since its DNS entry is not immediately available just after the provisioning. So, once again: no inventory which could be useful for Ansible!

 * When ``ansible.plugins.terraform`` finishes Terraform returns the IPv4 address of the newly deployed virtual machine in my LAN. The playbook then waits for the IPv4 to become reachable, since the virtual machine reboots near the end of its provisioning.
 
* When the newly provisioned virtual machine is reachable, I employ ``ansible.builtin.shell`` on ``localhost`` and I fire a SSH client against the newly provisioned virtual machine in order to retrieve its ``host key``.

```yaml
    - name: Obtain host key
      shell: "ssh -i {{ansible_ssh_private_key_file}} -o StrictHostKeyChecking=no {{provisioned_user}}@{{provisioned_host}} cat /etc/ssh/ssh_host_ed25519_key.pub"
      register: host_key
```

* In possession of the ``host key``, I insert it into my ``~/.ssh/known_hosts`` which, from this point on, will allow Ansible to connect to it as usual, without complaining about incorrect keys.

* From this point on, Ansible fires several commands against the newly deployed virtual machine, for example:

```yaml
    - name: Creating directories for applications
      file:
        path:  "{{item['path']}}"
        src:   "{{item['src']|default(omit)}}"
        state: "directory"
      loop: "{{folders.app1}} + {{folders.app2}} + {{folders.app3}}"
      delegate_to: "{{provisioned_host}}"
      remote_user: "{{provisioned_user}}"
      become: true
```

In regards to ``ansible-role-k3s``, I would like to do something more or less like this below:

```yaml
    - include_role:
        name: xanmanning.k3s
      vars:
         delegate_to: "{{provisioned_host}}"
         remote_user: "{{provisioned_user}}"
         k3s_build_cluster: false
```

I hope I've clarified the scenario. 

----

In regards to ``geerlingguy.docker``... I'm not really aware of it... but trying to answer your question: I've tried ``podman`` before on the newly provisioned virtual machine. The code is shown below:

```yaml
- name: Install podman
  package:
    name: podman
    state: present
  delegate_to: "{{provisioned_host}}"
  remote_user: "{{provisioned_user}}"
  become: true

- name: Configure registries for podman
  copy:
    dest: /etc/containers/registries.conf
    mode: u=rw,g=r,o=r
    owner: root
    group: root
    content: |
      [registries.search]
      registries = ['docker.io']
  delegate_to: "{{provisioned_host}}"
  remote_user: "{{provisioned_user}}"
  become: true
```

... as you can see... ``delegate_to`` all over the place.

**Comment by frgomes** [comment]
**Note**: I know Ansible less than you think. I'm not aware of  [dynamically](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html) and [AWS dynamic inventory](https://devopscube.com/setup-ansible-aws-dynamic-inventory/). I will have a look.

**Comment by frgomes** [comment]
Apparently, dynamic inventories will not work because the inventory is always evaluated when Ansible starts, does not matter if the inventory is a immutable file or a script which dynamically discovers a bunch of IP addresses. In my use case, I need to evaluate the inventory along the way, after provisioning the virtual machine and before executing further other tasks.

However, I guess it would work if I split my playbook into two playbooks. The firstplay book is responsible for provisioning, waiting for the virtual machine to be reachable and retrieving the host key. Then the last thing the first playbook does is kicking off the second playbook, which is responsible for all further tasks, like this:

```yaml
- name: Kicks off the second playbook, passing the IP address of the recently provisioned virtual machine
  shell: "ansible-playbook -i '{{provisioned_host}},' second_playbook,yaml
```

This approach seems to work. This is a proof of concept:

file: first_playbook.yml
```yaml
---
- name: This is the first playbook
  hosts: localhost

  tasks:

    - name: set facts -- obtain hostname
      shell: "cat /etc/hostname"
      register: hostname
     
    - name: debug
      debug:
        msg: "This is the first playbook: hostname is {{hostname.stdout}}"

    - name: set facts -- provisioned_ip
      set_fact:
        provisioned_host: "192.168.3.152"

    # see: ansible-doc -t inventory host_list
    - name: Kicks off the second playbook, passing the IP address of the recently provisioned virtual machine
      shell: "ansible-playbook -i '{{provisioned_host}},' {{playbook_dir}}/second_playbook.yml"
```

file: second_playbook.yml
```yaml
---
- name: This is the second playbook
  hosts: all

  tasks:

    - name: set facts -- obtain hostname
      shell: "cat /etc/hostname"
      register: hostname
          
     
    - name: debug
      debug:
        msg: "This is the second playbook: hostname is {{hostname.stdout}}"
```

Now call ``first_playbook``:

    ansible-playbook -vv first_playbook.yml

---

I will try this approach with ``ansible-role-k3s`` and let you know. Thanks

**Comment by xanmanning** [comment]
Yeah, you will find consumption of community Ansible roles a heck of a lot easier if you can connect to target hosts directly via SSH rather than using `delegate_to` - This k3s role does delegation in order to perform certain tasks anyway where the initial control plane node has to perform a specific action - changing this behavior will just break the role.

You could use Ansible to build an inventory from this initial build step before moving on to the configuration of K3S. I have done this with Terraform building VMs in Azure - the output IPs are then put into an inventory file for Ansible to consume.

**Comment by frgomes** [comment]
Yes, it works. This is my ``second_playbook.yml``:

```yaml
---
- name: This is the second playbook
  hosts: all

  tasks:

    - include_role:
        name: xanmanning.k3s
      vars:
        k3s_become_for_all: true
        ansible_python_interpreter: /usr/bin/python3
```
