### ISSUE TITLE
When write-kubeconfig-mode is 0640 it becomes 416

### ISSUE THREAD

**Issue by kenorb** [PyratLabs/ansible-role-k3s#157]
### Summary

I was confused by `write-kubeconfig-mode` when I set to:

```
        k3s_server:
          write-kubeconfig-mode: 0640
```

then it become `416`.

And when setting `0644`, it becomes `420`.

```
TASK [xanmanning.k3s : Ensure k3s config file exists] *********************************************************************************************************************************************************************************
--- before: /etc/rancher/k3s/config.yaml
+++ after: ~/.ansible/tmp/ansible-local-139192q1sfps3o/tmp637j2xa_/config.yaml.j2
@@ -8,5 +8,5 @@
 - foo=bar
 - hello=world
 with-node-id: true
+write-kubeconfig-mode: 416
```

Normally when you do 0640 with `chmod` command it works fine.

Is that expected behaviour?

### Issue Type

- Bug Report

### Controller Environment and Configuration

```text
$ ansible --version
ansible [core 2.11.5] 
$ ansible-galaxy list
- xanmanning.k3s, v2.11.0
```

### Steps to Reproduce

```yaml
---
- hosts: vm01
  roles:
    - role: xanmanning.k3s
      vars:
        k3s_become_for_install_dir: true
        k3s_become_for_usr_local_bin: true
        k3s_server:
          write-kubeconfig-mode: 0640
        k3s_state: installed
```
