### ISSUE TITLE
Using Calico Fails to Complete Install

### ISSUE THREAD

**Issue by carpenike** [PyratLabs/ansible-role-k3s#16]
How do you handle the "Wait for all nodes to be ready" phase when not using Flannel? I believe I need to load calico via kubectl, but the install will fail here prior to getting to a point where I can run the kubectl load command: https://github.com/PyratLabs/ansible-role-k3s/blob/df253b504a0537f764968276b2c4f97c20cf6a9c/tasks/build/configure-k3s-cluster.yml#L68-L77

**Comment by carpenike** [comment]
While that phase was running, I opened up another console and ran the `kubectl apply -f <manifest file>` command and it allowed the install to proceed.

Nodes stay in a `NotReady` state until their CNI is loaded.

**Comment by xanmanning** [comment]
I believe there is some logic here that is perhaps missing, I've not stumbled upon this as I still use flannel.

  1. In the current state the "Wait for nodes to be ready" task probably should not be run when `k3s_no_flannel` is defined as you need to.
  1. The role may benefit from a mechanism, say a variable, that will trigger some tasks to deploy of another CNI provider such as Calico. This should happen before the aforementioned task that is causing issues here.

Thoughts?

**Comment by carpenike** [comment]
> In the current state the "Wait for nodes to be ready" task probably should not be run when k3s_no_flannel is defined as you need to.
I think this would be the quickest fix as it wouldn't require you to support every other CNI up front, but still enable different CNIs to be used if admin knows what they're doing.

> The role may benefit from a mechanism, say a variable, that will trigger some tasks to deploy of another CNI provider such as Calico. This should happen before the aforementioned task that is causing issues here.

This would be good too, but I think it'd make sense to define _which_ CNIs you'd like to support first, otherwise that list can get unwieldly.

**Comment by carpenike** [comment]
Also, will add, because that looks to be the very last step in your role, it appears that the risk is fairly low by skipping it.

**Comment by xanmanning** [comment]
For now I am just going to skip the check, if there's enough demand I'll see if I can support some alternative CNIs but for now the low risk approach has been taken.

Thanks @carpenike

**Comment by jonathandey** [comment]
+1 for this

**Comment by xanmanning** [comment]
@jonathandey - see: https://github.com/PyratLabs/ansible-role-k3s/blob/main/documentation/configuration/use-an-alternate-cni.md

**Comment by jonathandey** [comment]
@xanmanning - in our custom resources YAML file we are defining the `spec.calicoNetwork.ipPools[0].cidr` key. Do we still need to do this?
If so, do you know if it is possible to template the value so it matches that of `k3s_server.cluster-cidr`?

**Comment by xanmanning** [comment]
You will need both AFAIK, as the K3s config will be like running the `kubeadm init --pod-network-cidr=INSERT_CIDR_HERE` step mentioned in the Calico quickstart.

You can potentially make the custom resources YAML a jinja2 template (you don't have to specify a `.yaml.j2` file extension, but I would recommend it so it's easy to spot). This would ensure the values match.

I've not tried it, but I believe the following example would work:

#### `custom-resources.yaml.j2`

```yaml
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.18/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: {{ k3s_server['cluster-cidr'] }}
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
```

You're then looking at this as your config:

```yaml
---

# K3S Server config, don't deploy flannel and set cluster pod CIDR.
k3s_server:
  cluster-cidr: 192.168.0.0/16
  flannel-backend: "none"

# Deploy the following k3s server templates.
k3s_server_manifests_templates:
  - "manifests/calico/tigera-operator.yaml"
  - "manifests/calico/custom-resources.yaml.j2"  # or whatever you call your jinja2 template
```

Hopefully this helps?
