### ISSUE TITLE
k3s_control_token not working

### ISSUE THREAD

**Issue by niklasweimann** [PyratLabs/ansible-role-k3s#187]
### Summary
When i set the `k3s_control_token` variable. The primary node initialises with a generated token and the secondary node tries to join the cluster with the token provided by `k3s_control_token` which obviously does not work.

### Issue Type

- Bug Report

### Steps to Reproduce

Try to setup the k3s cluster with an external ha database.
Set the k3s_control_token with some value.
The primary node, which initializes the cluster will not use the token, but the secondary nodes will try to use the token.
=> Cluster can not be initialized.

```yaml
k3s_cluster:
      vars:
        k3s_registration_address: 10.0.0.1
        k3s_control_token: <Some random string>
```

### Expected Result
I expect the secondary Nodes to correctly join the cluster initialized by the primary node.

### Actual Result
s. above
