### ISSUE TITLE
k3s_registries always defined

### ISSUE THREAD

**Issue by matteyeux** [PyratLabs/ansible-role-k3s#205]
### Summary

Looking at the task `Ensure containerd registries`, it is run when `k3s_registries is defined`:
```
- name: Ensure containerd registries
  ansible.builtin.include_tasks: ensure_containerd_registries.yml
  when:
    - k3s_registries is defined
    - ('rootless' not in k3s_runtime_config or not k3s_runtime_config.rootless)
```

But turns out, `k3s_registries` is always defined in [defaults](https://github.com/PyratLabs/ansible-role-k3s/blob/de1bd094e55b4c7b796bafc83fc55e6cb157b14f/defaults/main.yml#L138). Is there a way to skip the installation of the file registries.yml without removing the include_tasks? 

### Issue Type

- Bug Report

### Controller Environment and Configuration

Using latest version of the role

### Steps to Reproduce
run the role
