### ISSUE TITLE
K3s installation causes external-ip to show up as internal-ip

### ISSUE THREAD

**Issue by clrxbl** [PyratLabs/ansible-role-k3s#37]
![image](https://user-images.githubusercontent.com/28601081/88812304-dae6ca80-d1b7-11ea-8516-7fc1211641fc.png)

Screenshot of the INTERNAL-IP & EXTERNAL-IP in `kubectl get nodes -o wide`

Facts are set but I have no clue why it's not following them for setting the external-ip:

```
k3s_node_ip_address: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_tls_san: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_bind_address: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_external_address: "{{ vars['ansible_'~iface].ipv4.address }}"
```

**Comment by xanmanning** [comment]
Hi @clrxbl 

Not sure how to recreate this, would you be able to provide some more context about your setup? K3s versions for example? I've spun up 3 EC2 instances in AWS running v1.18.6+k3s1 and got the following result:

![Screenshot from 2020-08-01 08-59-41](https://user-images.githubusercontent.com/244186/89097296-a9e3e100-d3d5-11ea-8419-4949659cce24.png)

Here's the trimmed down version of my `hosts.yml` file run from my laptop:

```yaml
---

k8s_cluster:
  hosts:
    ironkube:
      # REDACTED
    juicykube:
      # REDACTED
    aws-euw2-k3s-01:
      ansible_user: ubuntu
      ansible_host: 18.133.REDACTED
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /home/xmanning/.ssh/id_rsa
    aws-euw2-k3s-02:
      ansible_user: ubuntu
      ansible_host: 3.10.REDACTED
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /home/xmanning/.ssh/id_rsa
    aws-euw2-k3s-03:
      ansible_user: ubuntu
      ansible_host: 18.130.REDACTED
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /home/xmanning/.ssh/id_rsa

aws_k8s:
  hosts:
    aws-euw2-k3s-01:
    aws-euw2-k3s-02:
    aws-euw2-k3s-03:
```

Playbook for creating this k3s cluster in AWS:

```yaml
---
- name: Converge
  hosts: aws_k8s
  vars:
    k3s_release_version: v1.18
    k3s_install_dir: /usr/local/bin
    k3s_become_for_all: true
  pre_tasks:
    - name: Ensure hostname is set
      become: true
      hostname:
        name: "{{ inventory_hostname }}"

  roles:
    - role: xanmanning.k3s
```

Versions:

```text
[ xmanning@dreadfort:~ ] $ ansible --version
ansible 2.8.5
  config file = /home/xmanning/.ansible.cfg
  configured module search path = [u'/home/xmanning/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.18rc1 (default, Apr  7 2020, 12:05:55) [GCC 9.3.0]

[ xmanning@dreadfort:~ ] $ cat .ansible/roles/xanmanning.k3s/meta/.galaxy_install_info 
{install_date: 'Sat Jun 13 16:04:54 2020', version: v1.7.2}
```

**Comment by clrxbl** [comment]
You seem to be having a similar issue though, unless you disabled the public ethernet interface on your EC2 instances. EXTERNAL-IP is empty.

**Comment by clrxbl** [comment]
Actually, hmm this issue seems to occur w/ plain K3s without Ansible aswell. Wonder if there's a way for me to set the internal & external IP. Probably will have to create an issue at K3s then.

**Comment by xanmanning** [comment]
Sorry,

I misinterpreted, I was assuming it was to do with your INTERNAL-IP showing a publicly routable IP address rather than an a private LAN IP.

Yes, in the [documentation](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#agent-networking) the flag `--node-external-ip` is described as the bellow

> External IP address to advertise for node

I have set it and got the same result:

![Screenshot from 2020-08-01 09-22-29](https://user-images.githubusercontent.com/244186/89097639-98e89f00-d3d8-11ea-85c7-11a73feef07c.png)

**Comment by clrxbl** [comment]
![image](https://user-images.githubusercontent.com/28601081/89097789-7d829180-d3e2-11ea-9e32-41a0becdb334.png)

Would it be possible to set the INTERNAL-IP somehow?

k3s_node_id: "{{ ansible_hostname | to_uuid }}"
k3s_node_ip_address: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_tls_san: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_bind_address: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_node_external_address: "{{ vars['ansible_'~iface].ipv4.address }}"

I'm trying to make everything bind to the VLAN network, but it's not setting either the INTERNAL or EXTERNAL IP to what I want.

**Comment by xanmanning** [comment]
Should `k3s_node_ip_address` be your VLAN and `k3s_node_external_address` the external IP address?

I don't know what setting `k3s_node_ip_address` and `k3s_node_external_address` will do. I've just destroyed my EC2 instances and am away from my PC to check.

Either way, if the expected behavior it to have them the same this might be one for Rancher.

**Comment by clrxbl** [comment]
They're all set to the same VLAN IP actually, so both INTERNAL-IP & EXTERNAL-IP should've been set to my VLAN IP, but the screenshot shows INTERNAL-IP being set to the external IP & EXTERNAL-IP being empty.

**Comment by xanmanning** [comment]
Hi @clrxbl,

I'm still trying to recreate this but I can't - I've set both `k3s_node_ip_address` and `k3s_node_external_address` to my private IP range in my AWS VPC, I've got the master node listening on this private address, as well as all he agents connecting to this private IP. 

```yaml
---
- name: Converge
  hosts: aws_k8s
  vars:
    k3s_release_version: v1.18
    k3s_install_dir: /usr/local/bin
    k3s_become_for_all: true
    iface: eth0
    k3s_control_node_address: "{{ hostvars['aws-euw2-k3s-01']['ansible_'~iface].ipv4.address }}"
    k3s_node_ip_address: "{{ vars['ansible_'~iface].ipv4.address }}"
    k3s_node_external_address: "{{ vars['ansible_'~iface].ipv4.address }}"
    k3s_bind_address: "{{ vars['ansible_'~iface].ipv4.address }}"
  pre_tasks:
    - name: Ensure hostname is set
      become: true
      hostname:
        name: "{{ inventory_hostname }}"

    - debug:
        var: hostvars['aws-euw2-k3s-01']['ansible_'~iface].ipv4.address

  roles:
    - role: xanmanning.k3s
```

https://asciinema.org/a/cfO6eCcEOOIXh68E5h71V4pQw

![Screenshot from 2020-08-01 14-40-45](https://user-images.githubusercontent.com/244186/89102879-2641e880-d405-11ea-99e0-9368dc2db44b.png)

I will admit that when I set `k3s_tls_san` to the IP I get a different issue that means my agents won't conect:

> `Aug 01 13:46:13 aws-euw2-k3s-01 k3s[12222]: I0801 13:46:13.448961   12222 log.go:172] http: TLS handshake error from 172.31.12.210:60644: EOF`

![Screenshot from 2020-08-01 14-47-36](https://user-images.githubusercontent.com/244186/89102979-1c6cb500-d406-11ea-987d-5367a1194ab9.png)

What happens if you remove `k3s_tls_san` - does it all connect OK?

**Comment by clrxbl** [comment]
Without k3s_tls_san, they connect & ready just fine. The issue still persists however.

```
# This should be set to a private network interface
iface: eth1

#Ansible SSH port, can also be set per host in hosts.ini
ansible_port: 22

# etcd configuration
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_protocol: http
etcd_advertise_client_urls: http://10.110.0.3:2379
etcd_initial_cluster_token: etcd-cluster-1

# k3s configuration
k3s_release_version: stable
k3s_control_node: true
k3s_become_for_all: true
k3s_cluster_domain: ansible.iptables.sh
k3s_control_node_address: 10.110.0.3
k3s_datastore_endpoint: http://10.110.0.3:2379
k3s_node_id: "{{ ansible_hostname | to_uuid }}"
k3s_node_ip_address: "{{ vars['ansible_'~iface].ipv4.address }}"
#k3s_tls_san: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_bind_address: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_node_external_address: "{{ vars['ansible_'~iface].ipv4.address }}"
k3s_install_hard_links: true # For system upgrade controller support

#For Calico
k3s_no_flannel: true
k3s_cluster_cidr: 192.168.0.0/16

#Disable Traefik
k3s_no_traefik: true
k3s_no_servicelb: true
```

Is my current fact config

**Comment by xanmanning** [comment]
Can you try again without `k3s_node_id` ? It seems setting this is causing me some issues.

**Comment by clrxbl** [comment]
Removing k3s_node_id solves the issue
![image](https://user-images.githubusercontent.com/28601081/89104049-9efd7080-d416-11ea-92d3-17b999baa2f8.png)

**Comment by xanmanning** [comment]
I think this is how you would add a node ID - I don't know why it doesn't give an EXTERNAL-IP when it is set unless it's a DNS issue?

**Comment by xanmanning** [comment]
![Screenshot from 2020-12-12 17-55-19](https://user-images.githubusercontent.com/244186/101991245-49c64b00-3ca3-11eb-8dc3-4e90d97d2b62.png)

Hi. I suspect this has been fixed in upstream k3s.

Below is my example config for v2.1.1 of this role:

```yaml
    k3s_become_for_all: true
    k3s_release_version: v1.19
    k3s_install_hard_links: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true
    interface_name: enp0s8
    ansible_interface: "ansible_{{ interface_name }}"
    k3s_server:
      disable:
        - servicelb
        - local-storage
      write-kubeconfig-mode: 0664
      advertise-address: "{{ hostvars[inventory_hostname][ansible_interface].ipv4.address }}"
      bind-address: 0.0.0.0
    k3s_agent:
      flannel-iface: "{{ interface_name }}"
      with-node-id: true
      node-ip: "{{ hostvars[inventory_hostname][ansible_interface].ipv4.address }}"
      node-external-ip: "{{ hostvars[inventory_hostname].ansible_enp0s9.ipv4.address }}"
      node-name: "{{ inventory_hostname }}"
      node-label:
        - "NodeID={{ inventory_hostname }}"
      kubelet-arg:
        - "volume-plugin-dir=/var/lib/rancher/k3s/agent/kubelet/plugins_registry"
    k3s_server_manifests_templates:
      - "{{ playbook_dir }}/../templates/00-metallb.yaml"
      - "{{ playbook_dir }}/../templates/05-metallb-arp-config.yaml"
      - "{{ playbook_dir }}/../templates/10-longhorn-operator.yaml"
```
