### ISSUE TITLE
Destination /usr/local/bin is not writable

### ISSUE THREAD

**Issue by danielo515** [PyratLabs/ansible-role-k3s#40]
Hello,
Thank you for this role.

I am folowing the most basic setup provided, and I am running into the following error:

```
Destination /usr/local/bin is not writable
```

The target is an ubuntu server:
```
Linux lab01 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

 this is the specific playbook I'm using:

```
- name: Rancher nodes
  hosts: rancher
  become: yes
  roles:
    - { role: xanmanning.k3s, k3s_release_version: v1.16.15+k3s1 }
```

Not sure what I can do about it
