### ISSUE TITLE
Consider moving to a file based config

### ISSUE THREAD

**Issue by onedr0p** [PyratLabs/ansible-role-k3s#53]
Keeping up with IaC, do you think it would be wise to move to this method of config instead of flags in the systemd service?

This is only supported in v1.19+ and would be breaking change. Maybe then is a good time to lock the 1.x release of this role and create a 2.x release that only supports k3s 1.19+

https://rancher.com/docs/k3s/latest/en/installation/install-options/#configuration-file

**Comment by onedr0p** [comment]
Do you also think that this would eliminate the need to have separate key names? We could literally just build the config.yaml from a parent key (k3s_config) and dump the children objects inthe config.yaml file, e.g...

```yaml
k3s_config:
  write-kubeconfig-mode: "0644"
  tls-san:
  - "foo.local"
  node-label:
  - "foo=bar"
  - "something=amazing"
```

I think that would be pretty awesome.
