### ISSUE TITLE
all nodes joined as masters

### ISSUE THREAD

**Issue by martinfriedrich** [PyratLabs/ansible-role-k3s#61]
while experimenting with a rpi cluster all nodes are joined as master
how can i join the nodes as non master?

i am using the master branch of the ansible role

# nodes
```
NAME    STATUS   ROLES    AGE   VERSION        INTERNAL-IP      EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
rpi01   Ready    master   25h   v1.19.3+k3s1   192.168.10.101   192.168.2.101   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
rpi07   Ready    master   25h   v1.19.3+k3s1   192.168.10.107   192.168.2.107   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
rpi02   Ready    master   25h   v1.19.3+k3s1   192.168.10.102   192.168.2.102   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
rpi06   Ready    master   25h   v1.19.3+k3s1   192.168.10.106   192.168.2.106   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
rpi04   Ready    master   25h   v1.19.3+k3s1   192.168.10.104   192.168.2.104   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
rpi05   Ready    master   25h   v1.19.3+k3s1   192.168.10.105   192.168.2.105   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
rpi03   Ready    master   25h   v1.19.3+k3s1   192.168.10.103   192.168.2.103   Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.0-k3s1
zbox    Ready    master   25h   v1.19.3+k3s1   192.168.10.100   192.168.2.100   Arch Linux           5.9.1-arch1-1      containerd://1.4.0-k3s1
```

# inventory
```
all:
  children:
    k3s_nodes:
      hosts:
        rpi01:
          ansible_host: 192.168.2.101
          k3s_advertise_address: 192.168.10.101
          k3s_control_node: 'true'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.101
          k3s_node_ip_address: 192.168.10.101
        rpi02:
          ansible_host: 192.168.2.102
          k3s_advertise_address: 192.168.10.102
          k3s_control_node: 'true'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.102
          k3s_node_ip_address: 192.168.10.102
        rpi03:
          ansible_host: 192.168.2.103
          k3s_advertise_address: 192.168.10.103
          k3s_control_node: 'false'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.103
          k3s_node_ip_address: 192.168.10.103
        rpi04:
          ansible_host: 192.168.2.104
          k3s_advertise_address: 192.168.10.104
          k3s_control_node: 'false'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.104
          k3s_node_ip_address: 192.168.10.104
        rpi05:
          ansible_host: 192.168.2.105
          k3s_advertise_address: 192.168.10.105
          k3s_control_node: 'false'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.105
          k3s_node_ip_address: 192.168.10.105
        rpi06:
          ansible_host: 192.168.2.106
          k3s_advertise_address: 192.168.10.106
          k3s_control_node: 'false'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.106
          k3s_node_ip_address: 192.168.10.106
        rpi07:
          ansible_host: 192.168.2.107
          k3s_advertise_address: 192.168.10.107
          k3s_control_node: 'false'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.107
          k3s_node_ip_address: 192.168.10.107
        zbox:
          ansible_host: 192.168.2.100
          k3s_advertise_address: 192.168.10.100
          k3s_control_node: 'true'
          k3s_flannel_interface: vlan2
          k3s_node_external_address: 192.168.2.100
          k3s_node_ip_address: 192.168.10.100
    ungrouped: {}
```

# vars

```
---
k3s_cluster_state: installed
k3s_release_version: v1.19.3+k3s1
k3s_build_cluster: true
k3s_use_experimental: true
k3s_datastore_endpoint: "mysql://XXXXXXX!@tcp(XXXXXX:3307)/k3s"
k3s_flannel_backend: "host-gw"
k3s_control_node_address: 192.168.10.100
```

**Comment by martinfriedrich** [comment]
i suspect something goes wrong at https://github.com/PyratLabs/ansible-role-k3s/blob/master/templates/k3s.service.j2#L17

shouldn't that line not be `{% if k3s_control_node is defined and variable is sameas true %}` ?

**Comment by xanmanning** [comment]
> i suspect something goes wrong at https://github.com/PyratLabs/ansible-role-k3s/blob/master/templates/k3s.service.j2#L17
> 
> shouldn't that line not be `{% if k3s_control_node is defined and variable is sameas true %}` ?
> 
> UPDATE: that doesn't work

Nope, `k3s_control_node` is always defined and I'm following lint [rule 601](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#don-t-compare-to-literal-true-false).

I'll take a look, not sure why all would be added as master. [Travis-CI](https://travis-ci.org/github/PyratLabs/ansible-role-k3s/jobs/739064560#L1134) test still comes back with the correct number of master nodes in molecule tests.

**Comment by xanmanning** [comment]
Think I have found it @martinfriedrich.

Try using `k3s_control_node: true` and `k3s_control_node: false` rather than `k3s_control_node: 'true'` and `k3s_control_node: 'false'` (remove single quotes).

Example playbook:

```yaml
---
- name: Converge
  hosts: aws_k8s
  vars:
    k3s_cluster_state: installed
    k3s_build_cluster: true
    k3s_release_version: v1.19.3+k3s1
    k3s_become_for_all: true
    k3s_datastore_endpoint: "mysql://k3s:SUPERDUPERSTRONGPASS@tcp(k3s-mysql.XXXXXXXXX.eu-west-2.rds.amazonaws.com:3306)/k3s"
    iface: eth0
    k3s_control_node_address: "{{ hostvars['k3s-node-01']['ansible_'~iface].ipv4.address }}"
    k3s_use_experimental: true
    k3s_flannel_backend: "host-gw"
    k3s_flannel_interface: "{{ iface }}"
  pre_tasks:
    - name: Ensure hostname is set
      become: true
      hostname:
        name: "{{ inventory_hostname }}"

  roles:
    - role: xanmanning.k3s
```

```text
[ xmanning@dreadfort:~ ] $ ansible --version
ansible 2.8.5
  config file = /home/xmanning/.ansible.cfg
  configured module search path = [u'/home/xmanning/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.18 (default, Aug  4 2020, 11:16:42) [GCC 9.3.0]
```

### With quotes.

```yaml
---
aws_k8s:
  hosts:
    k3s-node-01:
      ansible_user: ubuntu
      ansible_host: 3.9.19.133
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: 'true'
    k3s-node-02:
      ansible_user: ubuntu
      ansible_host: 35.176.90.54
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: 'true'
    k3s-node-03:
      ansible_user: ubuntu
      ansible_host: 35.178.86.240
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: 'false'
    k3s-node-04:
      ansible_user: ubuntu
      ansible_host: 35.177.83.206
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: 'false'
    k3s-node-05:
      ansible_user: ubuntu
      ansible_host: 18.130.199.65
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: 'false'
```

Result:

```text
root@k3s-node-01:~# kubectl get nodes -o wide
NAME          STATUS     ROLES    AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
k3s-node-04   Ready      master   23s   v1.19.3+k3s1   172.31.0.91     <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-02   Ready      master   34s   v1.19.3+k3s1   172.31.15.115   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-05   Ready      master   40s   v1.19.3+k3s1   172.31.2.174    <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-03   Ready      master   40s   v1.19.3+k3s1   172.31.10.204   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-01   Ready      master   65s   v1.19.3+k3s1   172.31.3.53     <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
```

### Without quotes

```yaml
---
aws_k8s:
  hosts:
    k3s-node-01:
      ansible_user: ubuntu
      ansible_host: 3.9.19.133
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    k3s-node-02:
      ansible_user: ubuntu
      ansible_host: 35.176.90.54
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    k3s-node-03:
      ansible_user: ubuntu
      ansible_host: 35.178.86.240
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false
    k3s-node-04:
      ansible_user: ubuntu
      ansible_host: 35.177.83.206
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false
    k3s-node-05:
      ansible_user: ubuntu
      ansible_host: 18.130.199.65
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false
```

Result:

```text
root@k3s-node-01:~# kubectl get nodes -o wide
NAME          STATUS   ROLES    AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
k3s-node-01   Ready    master   58s   v1.19.3+k3s1   172.31.3.53     <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-02   Ready    master   35s   v1.19.3+k3s1   172.31.15.115   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-03   Ready    <none>   19s   v1.19.3+k3s1   172.31.10.204   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-05   Ready    <none>   19s   v1.19.3+k3s1   172.31.2.174    <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
k3s-node-04   Ready    <none>   19s   v1.19.3+k3s1   172.31.0.91     <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-aws   containerd://1.4.0-k3s1
```
