### ISSUE TITLE
Ensure NODE_TOKEN is captured from control node: fatal

### ISSUE THREAD

**Issue by Christian-Rau** [PyratLabs/ansible-role-k3s#65]
### Summary

Running example playbook w/ 3 nodes.
### Issue Type
TASK [xanmanning.k3s : Ensure NODE_TOKEN is captured from control node] **********************************************************************
fatal: [node003 -> xx.xx.xx.xx]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}
fatal: [node002 -> xx.xx.xx.xx]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}

- Bug Report

### Controller Environment and Configuration

```text

```

### Steps to Reproduce

```yaml

```

### Expected Result

```text

```

### Actual Result

```text

```

**Comment by xanmanning** [comment]
Hi @Christian-Rau 

What happened to node001 before this task?

Please could you provide more information about:

- the playbook you are attempting to run? 
- What version of the role do you have installed?
- What variables are defined?

With very little information, I can only assume from the task `Ensure NODE_TOKEN is captured from control node` that the control plane has not started for some reason and a token has not been generated.

**Comment by Christian-Rau** [comment]
Hi, 
This happened earlier:
`fatal: [node001]: FAILED! => {"changed": false, "checksum_dest": null, "checksum_src": "f3240af4c2ce4a7f61910947095c935c30c71d41", "dest": "/usr/local/bin/k3s-v1.19.4+k3s1", "elapsed": 4, "msg": "Destination /usr/local/bin is not writable", "src": "/home/ansible/.ansible/tmp/ansible-tmp-1606770090.524077-18700-192205518764260/tmplxtzkkee", "url": "https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/k3s"`
Is it a database issue?
I am very new to k3s, and I have only used ansible for ad hoc server setups, I am confusing control node/host(´s´)? with server-managers/control-plane - and database server(s) - in this case?. So far I found out, it seems like the problem is, that I have no database connected,  As your documentation clearly states - the playbook will fail if no database is present.

I have a hard time picture the entire setup in my head, so I guess my question is this: how can I get a db for the cluster up and spinning the easiest/fastest possible way?
With 3 nodes - or 4 nodes?
 
Thank you very much for your fast reply.

**Comment by xanmanning** [comment]
Sorry for the late reply.

```text
fatal: [node001]: FAILED! => {"changed": false, "checksum_dest": null, "checksum_src": "f3240af4c2ce4a7f61910947095c935c30c71d41", "dest": "/usr/local/bin/k3s-v1.19.4+k3s1", "elapsed": 4, "msg": "Destination /usr/local/bin is not writable", "src": "/home/ansible/.ansible/tmp/ansible-tmp-1606770090.524077-18700-192205518764260/tmplxtzkkee", "url": "https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/k3s"
```
^^ This is a permissions error, your user doesn't have permission to write to `/usr/local/bin`

The user you're connecting to the OS with, does it have permission to run `sudo` without password? If not have you specified `--ask-pass` to prompt you for your password when running `ansible-playbook`?

If you have appropriate escalation privileges using sudo, what distribution are you using? Just making sure it's not OpenSUSE MicroOS or Fedora Silverblue, which are immutable distros which might affect where files can be written, I've not yet tested this role on these.

The following error:

```text
Unable to read /etc/rancher/k3s/k3s.yaml, please start server with — write-kubeconfig-mode to modify kube config permissions
error: Error loading config file “/etc/rancher/k3s/k3s.yaml”: open /etc/rancher/k3s/k3s.yaml: permission denied
```

Implies when running `kubectl` you are not running as root. You can fix this with the following which will make kubeconfig world-readable, any user will then be able to read this config:

```yaml
k3s_server:
    write-kubeconfig-mode: 0664
```

I would highly recommend you don't use `sudo chmod -R 777 /etc/rancher/k3s/k3s.yaml` - this makes the .yml file read-write-executable for everyone on the system, this can become very exploitable.

**Comment by cyclingwithelephants** [comment]
I'm also getting the same problem at the original issue 
```
TASK [xanmanning.k3s : Ensure k3s control plane is started] *******************************
skipping: [box]
ok: [nas]

TASK [xanmanning.k3s : Ensure NODE_TOKEN is captured from control node] *******************
fatal: [nas -> 192.168.50.75]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}
fatal: [box -> 192.168.50.75]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}

PLAY RECAP ********************************************************************************
box                        : ok=35   changed=0    unreachable=0    failed=1    skipped=30   rescued=0    ignored=0
nas                        : ok=45   changed=0    unreachable=0    failed=1    skipped=28   rescued=0    ignored=0
```

with the following command
```
ANSIBLE_NOCOWS=1 ansible-playbook playbook.yml -i inventory.yml
```
playbook
```yaml
# playbook.yaml
- name: Build a cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become_for_all: true
    k3s_server:
      write-kubeconfig-mode: 664
      service-node-port-range: 0-40000
      flannel-backend: 'wireguard'  # This needs to be in quotes for some reason
      disable:
        - traefik
        - servicelb
  roles:
    - xanmanning.k3s
```


and a host file
```yaml
k3s_cluster:
  hosts:
    # first host in order is the master by default with single master configurations.
    nas:
      ansible_host: 192.168.50.75
      ansible_user: root
      ansible_ssh_pass: <obfuscated>
    box:
      ansible_user: adam
      ansible_ssh_pass: <obfuscated>
      ansible_become_password: <obfuscated>
      ansible_host: 192.168.50.107
```

I don't see any other failed tasks up until this point. Happy to include further info upon request.

**Comment by xanmanning** [comment]
@cyclingwithelephants on "nas", what is the state of k3s service? `systemctl status k3s` after running? I suspect stopped and errored. Looks like it started then could not continue because of error.

I don't see `service-node-port-range` in [k3s server config documentation](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/).

**Comment by cyclingwithelephants** [comment]
Thanks for your quick reply,

I figured out it is indeed erroring due to `service-node-port-range: 0-40000` not being specified as a --kube-api-server argument (by removing this argument the playbook runs through, but I need to use the lower ports), is it possible to include this argument in the yaml syntax?

**Comment by xanmanning** [comment]
No problem, having trouble sleeping. Perhaps try:

```yaml
# playbook.yaml
- name: Build a cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become_for_all: true
    k3s_server:
      write-kubeconfig-mode: 664
      kube-apiserver-arg:
        - "service-node-port-range=0-40000"
      flannel-backend: 'wireguard'  # This needs to be in quotes for some reason
      disable:
        - traefik
        - servicelb
  roles:
    - xanmanning.k3s
```

**Comment by cyclingwithelephants** [comment]
It's worked, thank you so much! 

Hope you manage to get some sleep :)

**Comment by stevefan1999-personal** [comment]
Hi, I'm also running into this issue. I have designated several nodes to be workers and some to be masters, with master using embedded etcd database, and I will expand them in the future.

Here is my hosts:
```
[k3s:children]
k3s_master
k3s_worker

[k3s_worker]
foo
bar
baz

[k3s_master]
bigfoot
```

Here is my k3s var:
```yaml
---
k3s_release_version: v1.20.4+k3s1
```

Here is my k3s_master:
```yaml
---
k3s_control_node: true
k3s_etcd_datastore: true
k3s_use_unsupported_config: true

k3s_server:
  cluster-cidr: 172.24.0.0/16
  disable:
    - traefik
    - local-storage
  disable-network-policy: true
  flannel-backend: "none"
  # node-external-ip: '{{ external_ip }}'
  node-ip: '{{ internal_ip }}'
  node-label:
    - topology.kubernetes.io/region={{ datacenter }}-{{ region }}
    - topology.kubernetes.io/zone={{ datacenter }}-{{ region }}-{{ zone }}
```

Here is my k3s_worker:
```yaml
---
k3s_control_node: false

k3s_agent:
  kube-proxy-arg:
    - metrics-bind-address=0.0.0.0
  flannel-backend: "none"
  node-ip: '{{ internal_ip }}'
  node-label:
    - 'topology.kubernetes.io/region={{ datacenter }}-{{ region }}'
    - 'topology.kubernetes.io/zone={{ datacenter }}-{{ region }}-{{ zone }}'
    
```

I know k3s_server and k3s_agent can be merged but I prefer to separate them.

Now not only I wasn't able to do this, nor does the automatic delegation worked, my `bigfoot` node is not automatically selected as the primary node, and thus it stuck with `Waiting for /etc/rancher/k3s/cluster-token to be available`. I don't know why.

I have to update `bigfoot` to manually select it as primary node:
```
bigfoot k3s_primary_control_node=true
```

And I'm stuck with the similar problem OP faced:
```

TASK [xanmanning.k3s : Ensure cluster token is captured from control node] **************************************************************************************************************************************
ok: [bigfoot -> {{ internal_ip }}]
fatal: [foo -> {{ internal_ip }}]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/token"}
fatal: [bar -> {{ internal_ip }}]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/token"}
```

So as you see, it almost worked, all the workers are getting the right config, except this last step. 

My argument is because the agents/workers aren't running server mode, how could they even possibly have `/var/lib/rancher/k3s/server` let alone `/var/lib/rancher/k3s/server/token`? But I probably found a workaround, that is to supply the token myself.

If my interpretation in this project is right, this kind of heterogeneous/mixed cluster is not really supported in HA cluster, so it's either all of them are control nodes, or one of them is master and the rest is agents, or all of them are standalone.
