### ISSUE TITLE
Installation hangs on "Check that all nodes to be ready"

### ISSUE THREAD

**Issue by Diaoul** [PyratLabs/ansible-role-k3s#84]
### Summary

Installation hangs on "Check that all nodes to be ready" with 3 server nodes and etcd.

### Issue Type

- Bug Report

### Controller Environment and Configuration

```yaml
k3s_become_for_all: yes
k3s_install_hard_links: yes
k3s_etcd_datastore: yes

k3s_server:
  flannel-backend: 'none'
  disable:
    - servicelb
    - traefik
    - local-storage
    - metrics-server

k3s_control_node: yes
```

`sudo kubectl get nodes` gives:
```text
NAME                  STATUS     ROLES                       AGE   VERSION
k8s-node-1-25bc998c   NotReady   control-plane,etcd,master   25m   v1.20.2+k3s1
k8s-node-2-778e5b7e   NotReady   control-plane,etcd,master   23m   v1.20.2+k3s1
k8s-node-3-48330a77   NotReady   control-plane,etcd,master   23m   v1.20.2+k3s1
```

Here is the output of `sudo kubectl get pods -A`
```text
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-854c77959c-7k2cx   0/1     Pending   0          19m
```

After that I installed a CNI (Cilium) and:
```text
NAME                  STATUS   ROLES                       AGE   VERSION
k8s-node-1-25bc998c   Ready    control-plane,etcd,master   35m   v1.20.2+k3s1
k8s-node-2-778e5b7e   Ready    control-plane,etcd,master   33m   v1.20.2+k3s1
k8s-node-3-48330a77   Ready    control-plane,etcd,master   32m   v1.20.2+k3s1
```

I think the role isn't detecting correctly that I disabled flannel?

### Steps to Reproduce

Run the role with 3 nodes and the configuration as above.

### Expected Result

The role doesn't hang.

### Actual Result

Stuck on https://github.com/PyratLabs/ansible-role-k3s/blob/main/tasks/validate/state/nodes.yml

**Comment by xanmanning** [comment]
K3S issue rather than Ansible role issue. The nodes will never show as ready without a CNI.

You can install an alternative CNI to flannel by specifying the path to the manifest with: `k3s_server_manifests_templates`

**Comment by Diaoul** [comment]
Indeed they will never show as ready. This is why I think the role shouldn't expect them to be and this check skipped when flannel is disabled.
Or is there an alternative to disable that check? I do not understand the internals of the role and thus the `when` condition of this particular task:
```yaml
  when: k3s_control_node
        and (("disable" not in k3s_runtime_config)
            or ("disable" in k3s_runtime_config and "flannel" not in k3s_runtime_config.disable))
        and not ansible_check_mode
```

Should I put `flannel` in the `disable` config option?

Thank you for the alternative, I will look into it. I am not sure it is flexible enough to cover all the cases (like installation through Helm, etc.).

**Comment by Diaoul** [comment]
So I just tried that:
```yaml
k3s_become_for_all: yes
k3s_install_hard_links: yes
k3s_etcd_datastore: yes

k3s_server:
  flannel-backend: 'none'
  disable:
    - servicelb
    - traefik
    - local-storage
    - metrics-server
    - flannel

k3s_control_node: yes
```

and the check is skipped:
```text
TASK [xanmanning.k3s : Check that all nodes to be ready] **************************************************************************************
skipping: [k8s-node-1]
skipping: [k8s-node-2]
skipping: [k8s-node-3]
```

So I think the test should be changed to something like (untested):
```yaml
  when: k3s_control_node
        and (("flannel-backend" not in k3s_runtime_config)
            or ("flannel-backend" in k3s_runtime_config and k3s_runtime_config.flannel-backend != 'none'))
        and not ansible_check_mode
```
