### ISSUE TITLE
Task "Ensure the control node address is registered in Ansible" fails

### ISSUE THREAD

**Issue by funnym0nk3y** [PyratLabs/ansible-role-k3s#90]
### Summary

Running the role against a single node Pi 4 results in an error in "Ensure the control node address is registered in Ansible".

### Issue Type

- Bug Report

### Controller Environment and Configuration

```
# Begin ANSIBLE VERSION
ansible 2.10.5
  config file = None
  configured module search path = ['/home/ubuntu-bravo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu-bravo/.local/lib/python3.8/site-packages/ansible
  executable location = /home/ubuntu-bravo/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
# End ANSIBLE VERSION

# Begin ANSIBLE CONFIG

# End ANSIBLE CONFIG

# Begin ANSIBLE ROLES
# /home/ubuntu-bravo/.ansible/roles
- geerlingguy.docker, 3.0.0
- geerlingguy.pip, 2.0.0
- xanmanning.k3s, v2.5.2
# End ANSIBLE ROLES

# Begin PLAY HOSTS
["kube-01"]
# End PLAY HOSTS

# Begin K3S ROLE CONFIG
## kube-01

# End K3S ROLE CONFIG

# Begin K3S RUNTIME CONFIG
## kube-01
# End K3S RUNTIME CONFIG
```

### Steps to Reproduce

Those are the playbook and inventory files I'm using:

```yaml
---
- hosts: all
  become: true 

  vars:
    k3s_install_hard_links: true
    k3s_become_for_all: true
    

  roles:
    - xanmanning.k3s
```

```yaml
---
k3s_cluster:
  hosts:
    kube-01:
      ansible_user: ubuntu
      ansible_host: 192.168.2.101
      ansible_python_interpreter: /usr/bin/python3

```

### Expected Result

Playbook succeeds. 

### Actual Result

Tha playbook fails with:
`fatal: [kube-01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: \"hostvars['192.168.2.101']\" is undefined\n\nThe error appears to be in '/home/ubuntu-bravo/.ansible/roles/xanmanning.k3s/tasks/build/preconfigure-k3s.yml': line 89, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Ensure the control node address is registered in Ansible\n      ^ here\n"}`
